--#H2
CREATE TABLE carrinho (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   valor_total DOUBLE PRECISION NOT NULL,
   pagamento INT NOT NULL,
   CONSTRAINT pk_carrinho PRIMARY KEY (id)
);

CREATE TABLE carrinho_produto (
  carrinho_id BIGINT NOT NULL,
   produto_id BIGINT NOT NULL
);

ALTER TABLE carrinho_produto ADD CONSTRAINT fk_carpro_on_carrinho FOREIGN KEY (carrinho_id) REFERENCES carrinho (id);

ALTER TABLE carrinho_produto ADD CONSTRAINT fk_carpro_on_produto FOREIGN KEY (produto_id) REFERENCES produto (id);

--#MySQL
--CREATE TABLE carrinho (
--  id BIGINT AUTO_INCREMENT NOT NULL,
--   valor_total DOUBLE NOT NULL,
--   pagamento INT NOT NULL,
--   CONSTRAINT pk_carrinho PRIMARY KEY (id)
--);
--
--CREATE TABLE carrinho_produto (
--  carrinho_id BIGINT NOT NULL,
--   produto_id BIGINT NOT NULL
--);
--
--ALTER TABLE carrinho_produto ADD CONSTRAINT fk_carpro_on_carrinho FOREIGN KEY (carrinho_id) REFERENCES carrinho (id);
--
--ALTER TABLE carrinho_produto ADD CONSTRAINT fk_carpro_on_produto FOREIGN KEY (produto_id) REFERENCES produto (id);