--H2
CREATE TABLE carrinho (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   cliente_id BIGINT NOT NULL,
   produto_id BLOB NOT NULL,
   pagamento INT NOT NULL,
   CONSTRAINT pk_carrinho PRIMARY KEY (id)
);