--H2
CREATE TABLE compra (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   cliente_id BIGINT,
   pagamento INT NOT NULL,
   valor_total DOUBLE PRECISION NOT NULL,
   CONSTRAINT pk_compra PRIMARY KEY (id)
);

CREATE TABLE compra_produto (
  compra_id BIGINT NOT NULL,
   produto_id BIGINT NOT NULL
);

ALTER TABLE compra ADD CONSTRAINT FK_COMPRA_ON_CLIENTE FOREIGN KEY (cliente_id) REFERENCES cliente (id);

ALTER TABLE compra_produto ADD CONSTRAINT fk_compro_on_compra FOREIGN KEY (compra_id) REFERENCES compra (id);

ALTER TABLE compra_produto ADD CONSTRAINT fk_compro_on_produto FOREIGN KEY (produto_id) REFERENCES produto (id);